# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: delate

on:
  push:
    paths:
      - "delate.js"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 删除数据文件
        run: |
          git filter-branch --force --index-filter "git rm -rf --cached --ignore-unmatch class zdata zlog t.json z.json" --prune-empty --tag-name-filter cat -- --all
          git config --local user.email "ruytzzzgo@gmail.com"
          git config --local user.name "RuytzzZ"

          git push --force
